import { ApiItem } from '@microsoft/api-extractor-model';
import React, { FC } from 'react';
import { getApiItemTitle } from '../../utils/getApiItemTitle';
import { Breadcrumb } from './Breadcrumb';
import { Title } from './Title';

export const PageHeader: FC<Props> = ({ apiItem }) => (
  <>
    {
      '<!-- Do not edit this file. It is automatically generated by API Documenter. -->\n'
    }
    <Breadcrumb apiItem={apiItem} />
    <Title>{getApiItemTitle(apiItem)}</Title>
  </>
);

interface Props {
  apiItem: ApiItem;
}
