import { ApiItem, ApiItemKind } from '@microsoft/api-extractor-model';
import * as React from 'react';
import { Breadcrumb } from './components';
import { NamespacePage } from './NamespacePage';
import { NamespaceElementPage } from './NamespaceElementPage';

const namespaceKinds = [ApiItemKind.Namespace, ApiItemKind.Package];

export const Page: React.FC<Props> = ({ apiItem }) => (
  <>
    {
      '<!-- Do not edit this file. It is automatically generated by API Documenter. -->'
    }
    <Breadcrumb apiItem={apiItem} />
    {namespaceKinds.includes(apiItem.kind) ? (
      <NamespacePage apiItem={apiItem} />
    ) : (
      <NamespaceElementPage apiItem={apiItem} />
    )}
    {'\n'}
  </>
);

interface Props {
  apiItem: ApiItem;
}
